### ISSUE TITLE
[BUG] Several errors when compling firmware under Windows 11

### ISSUE THREAD

**Issue by seppelicous** [prusa3d/Prusa-Firmware-Buddy#3673]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** -MK4

**Printer firmware version** - 5.1.2

**Original or Custom firmware** - Original

**Optional upgrades** - [e.g. Filament Runout Sensor]

**Describe the bug**
  Please see the message below.

**How to reproduce**
  Download Soruce Code under "assets". 
Use this command: `python utils/build.py --preset mk4 --build-type release --bootloader yes --generate-bbf --generate-dfu --no-store-output --version-suffix=-BETA+5729.PR3570.B5 --version-suffix-short=-BETA+5729 -DCUSTOM_COMPILE_OPTIONS:STRING=-Werror -DDEVELOPMENT_ITEMS_ENABLED:BOOL=yes`

**Expected behavior**
  Compiling firmware 

`C:\Users\USER\Downloads\prusafirmware>python utils/build.py --preset mk4 --build-type release --bootloader yes --generate-bbf --generate-dfu --no-store-output --version-suffix=-BETA+5729.PR3570.B5 --version-suffix-short=-BETA+5729 -DCUSTOM_COMPILE_OPTIONS:STRING=-Werror -DDEVELOPMENT_ITEMS_ENABLED:BOOL=yes
Switching to Buddy's virtual environment.
You can disable this by setting the BUDDY_NO_VIRTUALENV=1 env. variable.

C:\Users\USER\Downloads\prusafirmware>Downloading ninja-1.10.2
Extracting ninja-1.10.2
Downloading cmake-3.22.5
Extracting cmake-3.22.5
Downloading gcc-arm-none-eabi-10.3.1
Extracting gcc-arm-none-eabi-10.3.1
Downloading clang-format-16-83817c2f
Extracting clang-format-16-83817c2f
Downloading bootloader-mini-2.3.4
Extracting bootloader-mini-2.3.4
Downloading bootloader-mk4-2.3.4
Extracting bootloader-mk4-2.3.4
Downloading bootloader-mk3.5-2.3.4
Extracting bootloader-mk3.5-2.3.4
Downloading bootloader-xl-2.3.4
Extracting bootloader-xl-2.3.4
Downloading bootloader-ix-2.3.4
Extracting bootloader-ix-2.3.4
Downloading mini404-0.9.10
Extracting mini404-0.9.10
Downloading cmsis-svd-0.4.9999
Extracting cmsis-svd-0.4.9999
Downloading CrashDebug-ae191d
Extracting CrashDebug-ae191d
Collecting ecdsa~=0.18 (from -r C:\Users\USER\Downloads\prusafirmware\requirements.txt (line 2))
  Using cached ecdsa-0.18.0-py2.py3-none-any.whl (142 kB)
Collecting polib~=1.2 (from -r C:\Users\USER\Downloads\prusafirmware\requirements.txt (line 3))
  Using cached polib-1.2.0-py2.py3-none-any.whl (20 kB)
Collecting pyyaml~=6.0 (from -r C:\Users\USER\Downloads\prusafirmware\requirements.txt (line 4))
  Obtaining dependency information for pyyaml~=6.0 from https://files.pythonhosted.org/packages/2b/9f/fbade56564ad486809c27b322d0f7e6a89c01f6b4fe208402e90d4443a99/PyYAML-6.0.1-cp312-cp312-win_amd64.whl.metadata
  Using cached PyYAML-6.0.1-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Collecting littlefs-python==0.8 (from -r C:\Users\USER\Downloads\prusafirmware\requirements.txt (line 5))
  Obtaining dependency information for littlefs-python==0.8 from https://files.pythonhosted.org/packages/09/8b/5b2f9b0b29a2bae7aee648259e92e798c259d6e1455ccbc79e92da0842e2/littlefs_python-0.8.0-cp312-cp312-win_amd64.whl.metadata
  Using cached littlefs_python-0.8.0-cp312-cp312-win_amd64.whl.metadata (5.8 kB)
Collecting numpy~=1.24.0 (from -r C:\Users\USER\Downloads\prusafirmware\requirements.txt (line 6))
  Using cached numpy-1.24.4.tar.gz (10.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 653, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_internal\utils\misc.py", line 697, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\Users\USER\Downloads\prusafirmware\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\USER\AppData\Local\Temp\pip-build-env-cd9qetak\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'`

**Comment by gudnimg** [comment]
I see you’re using Python 3.12. Not all dependencies support it yet. I recall on pytourch was left. 

For now I would use Python 3.11.7.  It at least works on my end and I use Windows 11 too.
