### ISSUE TITLE
[BFW-5405] [BUG] Enabling PrusaLink causes USBH_Thread crashed on USB drive inserted

### ISSUE THREAD

**Issue by jedahan** [prusa3d/Prusa-Firmware-Buddy#3723]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** MINI+

**Printer firmware version** - 5.1.2

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** - USB and PrusaConnect

**Describe the bug**
Enabling PrusaLink causes crash + bootloop if a usb drive is plugged in

**How to reproduce**
Enable PrusaLink with a working USB drive plugged into the printer. Observe USBH_Thread BSOD, task:IDLE? BSOD on bootloops, and watchdog resets.
Unplug the drive, and the printer will ask to write a crash dump to a usb drive after reboot, but if you plug in any usb drive to write the report to, it bootloops again.
Disable PrusaLink, and everything works fine. Same USB drive, different usb drive, doesn't matter.

**Expected behavior**
PrusaLink to not interfere with normal operations

**G-code** No GCode / printing required

**Crash dump file**
I cannot write the crash dump to usb, as plugging in a usb drive causes the crash

**Video**
Attached example screenshot of one of the BSODs, if requested I can create another video but I'm worried about getting the machine to an unrecoverable state.

![IMG_1049](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/32407/bd3041a3-606c-48dc-9741-2a4c6e0f1e09)

**Comment by jedahan** [comment]
Related to #3706

**Comment by danopernis** [comment]
I just tried that and wasn't able to reproduce it :disappointed:

**Comment by CZDanol** [comment]
Looks like BFW-5178 (internal ticket number). Has been fixed, should get out in the next release.

**Comment by mmajchrzycki** [comment]
I see the same issue on my Prusa MINI, however in my case the other component is crashing
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/6490687/029725df-f1f6-40a5-95c6-809fa1ec6d6c)

**Comment by tommie** [comment]
I just hada MINI 6.0.0 crash when uploading a file through PrusaLink, same as @mmajchrzycki. Sent a crash dump.

**Comment by CZDanol** [comment]
@tommie thanks, I've got the dump. I've created an internal ticket BFW-5405 to investigate it, hopefully it will give us something :)

**Comment by jedahan** [comment]
Very much appreciate the labels to help sync between private bug tracker and public one 🙏🏼

**Comment by mmajchrzycki** [comment]
The issue still exists on 6.0.1
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/6490687/6ae1fec2-7ec1-4694-94a6-7e1248e4232c)
[dump_buddy.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/15413505/dump_buddy.zip)

**Comment by tommie** [comment]
I don't know if I'm grasping at straws, but it feels like 6.0.1 has improved the situation. I've had maybe 1/10 (once since upgrade) crashing instead of something like 1/4.

**Comment by danopernis** [comment]
Which is still too many for my taste :disappointed:

I am sorry, I was looking into the crash dumps you provided but still don't understand the mechanism of the underlying issue. The Marlin task which periodically updates the watchdog seems to be running, so I don't understand why the watchdog reset triggered. Usually it is blocked by USB task, but not in this case, so I really don't understand.

This particular crash dump did not help me solve this issue, but please keep them coming if this happens again.

**Comment by MichalCadecky** [comment]
I am encountering the same issue as @mmajchrzycki. It happens both on 6.0.1 and 6.0.3 and PrusaSlicer 2.8.0. The upload starts, and just right after it, it crashes and reboots to the BSOD screen. Occasionally, before the upload starts, I see an error stating that there is not enough space on the USB. The second try to upload will end up with BSOD. I have sent my latest crash dump. Unfortunatelly, I do not have the crash dump from 6.0.1 :/

**Comment by tommie** [comment]
A new quarter is here. I've been on 6.0.4 since shortly after its release without any issue. Have done maybe 20 prints. Large and small files. Nowadays I only use PrusaLink for file transfers, so that should account for all of the prints.

I've had my suspicions that this is about some edge case in FAT that gets overwritten by the firmware, since it seems getting better over time for me, but new reports coming in. For that, let me add that the (included) USB stick is only used with my Prusa MINI, and when I did manual transfers, it was on a Ubuntu 20.04 or 22.04 machine. IIRC, it was never reformatted from when I got it with the printer.

**Comment by tommie** [comment]
Had my first two crashes on 6.0.4 now. First writing a new file with PrusaLink, it crashed. I managed to transfer and print that file with PrusaLink. When overwriting the file with PrusaLink, it crashed again.

Sent the first of the two.

**Comment by CZDanol** [comment]
6.0.4 is an outdated firmware, 6.1.3/4 being the current release, 6.2.0-alpha2 being the newest one. Please try updating.

**Comment by CZDanol** [comment]
We've been fixing number USB issues in 6.2.0

**Comment by tommie** [comment]
Ok, so seems 6.2.0 could be worth it. Will give it a spin. Thanks.

**Comment by tommie** [comment]
Got a crash on 6.2.0-alpha2+8702.

**Comment by CZDanol** [comment]
Crash dump, please :)

**Comment by tommie** [comment]
Yes, it's been sent.

**Comment by tommie** [comment]
I'm seeing crashes on v6.2.4 as well.

I've spent some time looking at crash dumps (with a byte-perfectly recreated ELF file of v6.2.4 to get symbols).

```
(gdb) bt
#0  crash_dump::trigger_crash_dump () at ./src/common/crash_dump/dump.cpp:354
#1  iwdg_warning_cb () at ./src/buddy/main.cpp:721
#2  0x08060ace in wdt_tick_1ms () at ./src/common/wdt.cpp:76
#3  wdt_tick_1ms () at ./src/common/wdt.cpp:57
#4  SysTick_Handler () at ./src/buddy/timing_sys.cpp:31
#5  <signal handler called>
#6  0x080a7cfc in USBH_MSC_RdWrProcess (phost=phost@entry=0x20007574 <hUsbHostHS>, lun=lun@entry=0 '\000') at ./lib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc.c:691
#7  0x080a7e48 in USBH_MSC_Read (phost=0x20007574 <hUsbHostHS>, lun=0 '\000', address=<optimized out>, pbuf=<optimized out>, length=1)
    at ./lib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc.c:827
#8  0x08062b38 in USBH_MSC_WorkerTask () at ./src/buddy/usbh_diskio.cpp:145
#9  0x080b86ec in vPortEnableVFP () at ./lib/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c:794
```

It's a watchdog timeout. The easiest solution is to feed the dog, but that's not the core issue.

In summary, the main issue is that the USB drive might be sending garbage. Instead of the MSC CSW transaction being 13 bytes, it's 64 bytes, and a continuation of the `DATA_IN` transaction.

This causes corrupted memory because [`csw` is 13 bytes (+3 padding)](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/818d812f954802903ea0ff39bf44376fb0b35dd2/lib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc/usbh_msc_bot.h#L121), but must be at least 64 bytes long, or the [USB IN transaction might overwrite](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/818d812f954802903ea0ff39bf44376fb0b35dd2/lib/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c#L1915-L1924) what comes after. Page 1445 on `OTG_HS_HCTSIZx` of [RM0090](https://www.st.com/resource/en/reference_manual/rm0090-stm32f405415-stm32f407417-stm32f427437-and-stm32f429439-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) says

> XFRSIZ: For an IN, this field is the buffer size that the application has reserved for the transfer. The application is expected to program this field as an integer multiple of the maximum packet size for IN transactions (periodic and nonperiodic)

What's overwritten includes `unit[0].capacity.block_size` and `unit[0].state` (both in `MSC_HandleTypeDef`.)

In my case, the state variable ends up being 73. This means `USBH_MSC_RdWrProcess` triggers the [default case](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/818d812f954802903ea0ff39bf44376fb0b35dd2/lib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc.c#L548), which does nothing. Thus `USBH_MSC_Read` is unable to make progress, and the watchdog times out.

If I add a check for the transaction being larger than 13 bytes in [USBH_MSC_DecodeCSW](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/818d812f954802903ea0ff39bf44376fb0b35dd2/lib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Src/usbh_msc_bot.c#L607), I can get it to trigger when the device tries to preload a gcode file on boot. So this is not just about PrusaLink.

----

My proposal is to make this 64 bytes (all URB code uses `BOT_CSW_LENGTH` as the length, so the this change doesn't matter for requested size):

https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/818d812f954802903ea0ff39bf44376fb0b35dd2/lib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc/usbh_msc_bot.h#L112-L123

and remove the `Reserved2` padding here:

https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/818d812f954802903ea0ff39bf44376fb0b35dd2/lib/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc/usbh_msc_bot.h#L125-L137

Alternatively, make `Reserved2` be 64-13=51 bytes.

----

There are still lots of unanswered questions, like why preload normally works, why this garbage data is sent.

If the number of people affected by this is going down, then perhaps the flash drive that was delivered with the MINI when I bought it is just misbehaving sometimes. I'm still using that. (Tried to Wireshark trace it while doing `dd` on my computer, but no luck. Maybe because the read size is 128 kiB, not 512 B.)

**Comment by tommie** [comment]
I haven't printed a lot since my debugging session, but with the proposed patch, I've had no crashes in ~10 prints.

**Comment by danopernis** [comment]
Hi @tommie thanks for all the investigation ❤️ It looks like your patch could work, we just want to make sure it works as expected and really understand why it works. I've bumped the internal issue priority and we will see if we can get your proposed patch merged. It will probably take several rounds of testing if we do.

**Comment by tommie** [comment]
Hi again. I think I just managed to trigger the bad USB behavior.

PrusaLink stopped at 10% upload, but there was no crash. The printer UI still works. However, I had to re-plug the USB stick for the printer to be able to access it again. After that, I was able to upload and print.

So I think I can confirm that this patch solves my hard crash, and that the expected error path is now kicking in if something goes wrong in communication, though the error seems mostly ignored.

**Comment by tommie** [comment]
I think the printer gets confused when the USB stick errors out, so after the non-crashing error occurs, I still have to reboot the printer, because it can't talk to the stick anymore. Possibly reconnecting the stick could help.

I've since switched to a new USB stick (remember, my issue was with the chrome one delivered with my Prusa Mini,) and don't seem to have any issues with this one.

However, I still think it's somewhat tragically funny that the bug has been identified, a small solution proposed, and almost a year later, you still let printers BSOD instead of gracefully error.
